// match-tracker-angular/src/app/components/navbar/navbar.component.ts
import { Component } from '@angular/core';
import { RouterModule } from '@angular/router';

@Component({
  selector: 'app-navbar',
  imports: [RouterModule],
  templateUrl: './navbar.component.html',
  styleUrl: './navbar.component.scss'
})
export class NavbarComponent {
  logo = 'logo.png'; // Путь к логотипу
}

<nav class="navbar">
  <div class="navbar-logo">
    <img [src]="logo" alt="Match Tracker Logo" />
  </div>
  <ul class="navbar-list">
    <li class="navbar-item">
      <a routerLink="/" routerLinkActive="active" class="navbar-link">Home</a>
    </li>
    <li class="navbar-item">
      <a routerLink="/heroes" routerLinkActive="active" class="navbar-link">Heroes</a>
    </li>
    <li class="navbar-item">
      <a routerLink="/items" routerLinkActive="active" class="navbar-link">Items</a>
    </li>
    <li class="navbar-item">
      <a routerLink="/teams" routerLinkActive="active" class="navbar-link">Teams</a>
    </li>
    <li class="navbar-item">
      <a routerLink="/tournaments" routerLinkActive="active" class="navbar-link">Tournaments</a>
    </li>
  </ul>
</nav>

// match-tracker-react/src/components/Navbar.jsx
import React from 'react';
import { NavLink } from 'react-router-dom';
import logo from '../assets/logo.png';
import '../styles/navbar.scss';

const Navbar = () => {
  return (
    <nav className="navbar">
      <div className="navbar-logo">
        <img src={logo} alt="Match Tracker Logo" />
      </div>
      <ul className="navbar-list">
        <li className="navbar-item">
          <NavLink to="/" className="navbar-link" activeclassname="active">
            Home
          </NavLink>
        </li>
        <li className="navbar-item">
          <NavLink to="/heroes" className="navbar-link" activeclassname="active">
            Heroes
          </NavLink>
        </li>
        <li className="navbar-item">
          <NavLink to="/items" className="navbar-link" activeclassname="active">
            Items
          </NavLink>
        </li>
        <li className="navbar-item">
          <NavLink to="/teams" className="navbar-link" activeclassname="active">
            Teams
          </NavLink>
        </li>
        <li className="navbar-item">
          <NavLink to="/tournaments" className="navbar-link" activeclassname="active">
            Tournaments
          </NavLink>
        </li>
      </ul>
    </nav>
  );
};

export default Navbar;
